function aptValidation
%APTVALIDATION estimates new candidates (which are generated by
%aptGenerateSequence) for given stats model.
%   'apt.vali.number' is number of newly generated candidates
%   'apt.vali.mode' is mode used for randomly generating new candidates.

global apt

if (~isfield(apt,'vali') || ~isfield(apt.vali,'number'))
    apt.vali.number = 1000;
end

if ~isfield(apt.vali,'mode')
    apt.vali.mode = 'random';
end

aptGenerateValiSequence;

aptPredictors(true);

if ~all(size(apt.vali.predNames)==size(apt.predNames)) || ~all(strcmp(apt.vali.predNames, apt.predNames))
    warning('Something went wrong!')
end

for iY = 1:length(apt.Y)
    if isfield(apt.config,'useLassoFit') && strcmp(apt.config.useLassoFit,'best')
        idx = apt.stats(iY).IndexMinMSE;
    else
        idx = apt.stats(iY).Index1SE;
    end
    apt.vali.estResponse{iY} = apt.stats(iY).Intercept(idx) + apt.vali.predX'*apt.stats(iY).beta(:,idx);
end
end