function [vali] = aptValidation(numberSamples)
%APTVALIDATION estimates new candidates (which are generated by
%aptGenerateSequence) for given stats model.
%   'numberSamples' is number of newly generated candidates
%   'apt.modeToGenerateNewSequences' is mode used for randomly generating new candidates.

global apt

if(~exist('numberSamples','var') || isempty(numberSamples))
    numberSamples = 1000;
end

if~isfield(apt,'modeToGenerateNewSequences')
    apt.modeToGenerateNewSequences = 'random';
end

validationIndex = apt.stats.Index1SE;

vali.number = numberSamples;
vali.beta = apt.stats.beta(:,validationIndex);
vali.intercept = apt.stats.Intercept(validationIndex);
sequenceTrue = apt.sequence;
predNamesTrue = apt.predNames;
XTrue = apt.predX;
aptGenerateSequence(vali.number);
vali.generatedSequence = apt.generatedSequence;
aptPredictors;

% Sanity check
if sum(cellfun(@strcmp,predNamesTrue, apt.predNames)) ~= length(apt.PredictorNames)
    apt.sequence = sequenceTrue;
    apt.predNames = predNamesTrue;
    apt.predX = XTrue;
    error('validation predictors do not match calibrated predictors!')
end

vali.EstRates = vali.intercept + X'*vali.beta;

apt.sequence = sequenceTrue;
apt.predNames = predNamesTrue;
apt.predX = XTrue;

end

